parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_pgsql'
                host: '%env(DATABASE_HOST)%'
                port: '%env(DATABASE_PORT)%'
                dbname: '%env(DATABASE_DBNAME)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'

            digesto_viejo:
                driver: 'pdo_mysql'
                host: '%env(DATABASE_DIGESTO1_HOST)%'
                port: '%env(DATABASE_DIGESTO1_PORT)%'
                dbname: '%env(DATABASE_DIGESTO1_DBNAME)%'
                user: '%env(DATABASE_DIGESTO1_USER)%'
                password: '%env(DATABASE_DIGESTO1_PASSWORD)%'
                server_version:   '5.7'
                charset: utf8

#        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
        entity_managers:
            default:
#                auto_generate_proxy_classes: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    datetime_functions:
                        YEAR:           Oro\ORM\Query\AST\Functions\SimpleFunction
#                        date:           Oro\ORM\Query\AST\Functions\SimpleFunction
#                        time:           Oro\ORM\Query\AST\Functions\SimpleFunction
#                        timestamp:      Oro\ORM\Query\AST\Functions\SimpleFunction
#                        convert_tz:     Oro\ORM\Query\AST\Functions\DateTime\ConvertTz

#        mappings:

