# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    # ...
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    default_config: my_config
    configs:
        my_config:
            toolbar: full
            extraPlugins: "justify, liststyle, lineheight"
            line_height: "1px;1.1px;1.2px;1.3px;1.4px;1.5px"
            removeButtons: 'Subscript,Superscript'
    plugins:
        justify:
            path:     "build/ckeditor/plugins/justify/" # with trailing slash
            filename: "plugin.js"
        liststyle:
            path:     "build/ckeditor/plugins/liststyle/" # with trailing slash
            filename: "plugin.js"
        lineheight:
            path:     "build/ckeditor/plugins/lineheight/" # with trailing slash
            filename: "plugin.js"


