# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_DIGESTO_ADMIN]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_DIGESTO_ADMIN: [ROLE_SUPER_ADMIN, ROLE_DIGESTO]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        user_db:
            entity: { class: UsuariosBundle\Entity\Usuario, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
#            logout_on_user_change: true
#            switch_user: { role: ROLE_ADMIN, parameter: _want_to_be_this_user }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrador-admin, role: ROLE_DIGESTO }
        - { path: ^/administrador, role: ROLE_DIGESTO }