twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'custom\fields.html.twig'
        - 'custom\image_widget.html.twig'
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
#    form_themes: ['bootstrap_3_horizontal_layout.html.twig']
    globals:
        app_version: '%env(APP_VERSION)%'
        app_name: '%env(APP_NAME)%'
        primary_color: '%env(APP_PRIMARY_COLOR)%'