vich_uploader:
    db_driver: orm
    mappings:
        normas:
            uri_prefix: '%app.path.normas_documentos%'
            upload_destination: '%kernel.project_dir%/public%app.path.normas_documentos%'
        textos_normas:
            uri_prefix: '%app.path.textos_normas%'
            upload_destination: '%kernel.project_dir%/public%app.path.textos_normas%'
        textos_definitivos_normas:
            uri_prefix: '%app.path.textos_definitivos_normas%'
            upload_destination: '%kernel.project_dir%/public%app.path.textos_definitivos_normas%'
        anexos:
            uri_prefix: '%app.path.anexos_documentos%'
            upload_destination: '%kernel.project_dir%/public%app.path.anexos_documentos%'
        boletin_oficial_municipal:
            uri_prefix: '%app.path.boletin_oficial_municipal_documentos%'
            upload_destination: '%kernel.project_dir%/public%app.path.boletin_oficial_municipal_documentos%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        documentos_web:
            uri_prefix: '%app.path.documentos_web%'
            upload_destination: '%kernel.project_dir%/public%app.path.documentos_web%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        documentos_anexos_web:
            uri_prefix: '%app.path.documentos_anexos_web%'
            upload_destination: '%kernel.project_dir%/public%app.path.documentos_anexos_web%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        recursos_web:
            uri_prefix: '%app.path.recursos_web%'
            upload_destination: '%kernel.project_dir%/public%app.path.recursos_web%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        consolidaciones:
            uri_prefix: '%app.path.consolidaciones%'
            upload_destination: '%kernel.project_dir%/public%app.path.consolidaciones%'
        anexos_consolidacion:
            uri_prefix: '%app.path.anexos_consolidacion%'
            upload_destination: '%kernel.project_dir%/public%app.path.anexos_consolidacion%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
