<?php

namespace App\Repository;

/**
 * LegajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegajoRepository extends \Doctrine\ORM\EntityRepository
{
}
