<?php

namespace App\Repository;

/**
 * TipoRelacionPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRelacionPersonaRepository extends \Doctrine\ORM\EntityRepository
{
}
