easy_admin:
    #    disabled_actions: ['delete']
    site_name: '%env(APP_NAME)%'
    show:
      max_results: 20
    list:
      actions:
        - { name: 'show', icon: 'eye', label: '' }
        - { name: 'edit', icon: 'pencil', label: '' }
    #            - { name: 'delete', icon: 'trash', label: '' }

    design:
        brand_color: '#17a867'
#        form_theme: ['horizontal']
        menu:
          - { label: 'Administración', route: 'administrador' }
          - { label: 'Ramas', entity: Rama }
          - { label: 'Usuarios', entity: Usuario }
          - { label: 'Boletín Oficial Municipal', entity: BoletinOficialMunicipal }
          - { label: 'Consolidación', entity: Consolidacion }
          - { label: 'Anexos Consolidación', entity: AnexoConsolidacion }
          - { label: 'Beneficiarios', entity: Beneficiario }
          - { label: 'Palabras Claves', entity: PalabraClave }
          - { label: 'Descriptores', entity: Descriptor }
          - { label: 'Identificadores', entity: Identificador }
          - { label: 'Tipo de Identificador', entity: TipoIdentificador }
        assets:
          favicon: 'bundles/app/img/favicon.png'