easy_admin:
    entities:
        Beneficiario:
            class: App\Entity\Beneficiario
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'apellido' }