easy_admin:
    entities:
        PalabraClave:
            class: App\Entity\PalabraClave
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'activo' }