easy_admin:
    entities:
        Rama:
            class: App\Entity\Rama
            form:
              fields:
                - { property: 'numeroRomano' }
                - { property: 'titulo' }
                - { property: 'orden' }
                - { property: 'activo' }