easy_admin:
    entities:
        Usuario:
            class: App\Entity\Usuario
            list:
                dql_filter: "entity.roles LIKE '%%ROLE_DIGESTO%%' or entity.roles LIKE '%%ROLE_DIGESTO_ADMIN%%'"
                fields:
                  - { property: 'username' }
                  - { property: 'email', type: 'email' }
                  - { property: 'enabled' }
                  - { property: 'lastLogin' }
            form:
                fields:
                  - username
                  - email
                  - enabled
                  - persona
                  #                    - lastLogin
                  # if administrators are allowed to edit users' passwords and roles, add this:
                  - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                  - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: false, choices:
                    { 'ROLE_USER': 'ROLE_USER',
                      'ROLE_ADMIN': 'ROLE_ADMIN',
                      'ROLE_DIGESTO': 'ROLE_DIGESTO',
                      'ROLE_DIGESTO_ADMIN': 'ROLE_DIGESTO_ADMIN'
                    }
                    }
                    }