# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'es'
    app_version: '%env(APP_VERSION)%'
    app_name: '%env(APP_NAME)%'
    app.path.normas_documentos: /uploads/normas
    app.path.textos_normas: /uploads/textos_normas
    app.path.textos_definitivos_normas: /uploads/textos_definitivos_normas
    app.path.anexos_documentos: /uploads/anexos_normas
    app.path.anexos_originales: /uploads/anexos_originales
    app.path.boletin_oficial_municipal_documentos: /uploads/documentos/boletin_oficial_municipal
    app.path.documentos_web: /uploads/documentos/documentos_web
    app.path.documentos_anexos_web: /uploads/documentos/documentos_anexos_web
    app.path.recursos_web: /uploads/recursos_web
    app.path.consolidaciones: /uploads/consolidaciones
    app.path.anexos_consolidacion: /uploads/consolidaciones/anexos
    app.path.textos_definitivos_consolidacion: /uploads/textos_definitivos_consolidacion

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #knp_menu
    app.menu_builder:
        class: App\Menu\Builder
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main }

    App\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main }

#    fos user
#    fos_user.user_manager:
#        class: FOS\UserBundle\Model\UserManagerInterface

    form.type.bootstrapcollection:
        class: UtilBundle\Form\Type\BootstrapCollectionType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: bootstrapcollection }
